pipeline {
 agent {
    docker {
      image 'maven:3.9.0-eclipse-temurin-17-alpine'
      copy {
                from './time'
                into '/app'
            }
    }
  }
  stages {
    stage('Copy project files') {
      steps {
        sh "cp . /app"
      }
    }
    stage('Build') {
      steps {
        sh "cd /app && mvn clean package"
      }
    }
    stage('Test') {
      steps {
        sh "cd /app && mvn test"
      }
    }
    // stage('Deploy') {
    //   steps {
    //     // // Implement your deployment logic here, e.g., using a deployment plugin
    //     // sh "cp /app/target/my-app.jar /deployment/path"
    //   }
    // }
  }
}